pub mod api;
#[cfg(feature = "desktop")]
pub mod config;
#[cfg(feature = "desktop")]
pub mod interrogator;
pub mod music;
pub mod music_audio_style;
pub mod music_cover;
pub mod music_link;
pub mod music_reference;
pub mod music_review;
#[cfg(feature = "desktop")]
pub mod novelai;
#[cfg(feature = "desktop")]
pub mod prompt_assistant;
#[cfg(feature = "desktop")]
pub mod server;
pub mod video_drafts;
pub mod video_export;
pub mod video_interpolate;
#[cfg(feature = "desktop")]
pub mod websocket;
#[cfg(feature = "desktop")]
pub mod workflow;
