pub mod api;
#[cfg(feature = "desktop")]
pub mod config;
#[cfg(feature = "desktop")]
pub mod interrogator;
#[cfg(feature = "desktop")]
pub mod prompt_assistant;
#[cfg(feature = "desktop")]
pub mod server;
pub mod video_export;
#[cfg(feature = "desktop")]
pub mod websocket;
#[cfg(feature = "desktop")]
pub mod workflow;
