// @generated by report-proxy/scripts/extract-catalog.mjs -- do not edit by hand.
// Regenerate after changing error copy in src/lib/locales/en.ts.

pub fn catalog_lookup(code: &str) -> Option<CatalogEntry> {
    Some(match code {
        "api_error_5xx" => CatalogEntry {
            title: "The server returned an error",
            what: "The backend responded with a server-side error (5xx).",
            why: "ComfyUI or the backend hit an internal error while handling the request.",
            fixes: "Retry in a moment. || Check the logs for the underlying error. || Restart ComfyUI if it keeps failing.",
        },
        "attention_backend_install" => CatalogEntry {
            title: "Attention backend install failed",
            what: "Installing the acceleration backend did not complete.",
            why: "The backend may not support your GPU, or the download or build failed.",
            fixes: "Try a different attention backend in Settings. || Confirm your GPU is supported. || Check the logs and retry the install.",
        },
        "checksum_mismatch" => CatalogEntry {
            title: "Downloaded file was corrupted",
            what: "The downloaded file did not match its expected checksum.",
            why: "The download was interrupted or altered in transit.",
            fixes: "Delete the partial file and download again. || Retry on a more stable connection. || If it keeps failing, report the URL.",
        },
        "civitai_auth" => CatalogEntry {
            title: "CivitAI login required",
            what: "CivitAI rejected the download as unauthorized.",
            why: "The file needs a CivitAI account or API key that is missing or invalid.",
            fixes: "Add or update your CivitAI API key in Settings. || Confirm the key has access to this file. || Sign in on civitai.com to check the file is still available.",
        },
        "comfyui_launch_failed" => CatalogEntry {
            title: "ComfyUI failed to start",
            what: "The app tried to launch ComfyUI but the process did not start.",
            why: "The install may be incomplete, a dependency is missing, or a port is in use.",
            fixes: "Re-run setup from Settings. || Check the logs for the launch error. || Make sure no other ComfyUI is already using the port.",
        },
        "comfyui_not_running" => CatalogEntry {
            title: "ComfyUI is not running",
            what: "The app needs ComfyUI running but could not find it.",
            why: "ComfyUI has not been started, crashed, or is still launching.",
            fixes: "Start ComfyUI from Settings. || Wait for startup to finish, then retry. || Check the logs for a ComfyUI crash.",
        },
        "connection_failed" => CatalogEntry {
            title: "Could not reach the server",
            what: "The app could not open a connection to the backend.",
            why: "The server or ComfyUI may be stopped, still starting up, or blocked by a firewall.",
            fixes: "Wait a few seconds and retry. || Check that ComfyUI is running in Settings. || Confirm no firewall or VPN is blocking localhost.",
        },
        "disk_full" => CatalogEntry {
            title: "Not enough disk space",
            what: "There was not enough free space to finish writing the file.",
            why: "The drive holding your models or output folder is full.",
            fixes: "Free up disk space and retry. || Point the models or gallery folder to a larger drive in Settings. || Delete unused models from Model Hub.",
        },
        "download_404" => CatalogEntry {
            title: "File not found (404)",
            what: "The download URL returned Not Found.",
            why: "The link is wrong, the file was moved or removed, or it needs a login the app does not have.",
            fixes: "Double-check the URL opens in a browser. || For Hugging Face, use a /resolve/ link, not a /blob/ page. || For gated files, add your access token in Settings.",
        },
        "download_network" => CatalogEntry {
            title: "Download failed",
            what: "The file could not be downloaded.",
            why: "The connection dropped, timed out, or the host was unreachable.",
            fixes: "Check your internet connection and retry. || Try again later if the host is busy. || Confirm no VPN or firewall is blocking the download.",
        },
        "generation_interrupted" => CatalogEntry {
            title: "Generation was stopped",
            what: "The generation did not finish.",
            why: "It was cancelled, or ComfyUI stopped partway through.",
            fixes: "Start the generation again. || Confirm ComfyUI is still running. || Check the logs if you did not cancel it.",
        },
        "generic" => CatalogEntry {
            title: "Something went wrong",
            what: "The app hit an error it did not have specific guidance for.",
            why: "This can happen from an unexpected state, a transient glitch, or a bug.",
            fixes: "Try the action again. || Restart the app, and ComfyUI if it is running. || If it keeps happening, report it with the Report this error button below.",
        },
        "hf_page_url" => CatalogEntry {
            title: "That is a Hugging Face page, not a file",
            what: "The URL points to a model page instead of a downloadable file.",
            why: "Hugging Face /blob/ links open a web page; downloads need a /resolve/ link.",
            fixes: "Use the /resolve/main/... form of the URL. || The app auto-fixes /blob/ links in the Model Hub field. || Copy the direct download link from the file's page.",
        },
        "invalid_workflow" => CatalogEntry {
            title: "The workflow was invalid",
            what: "The generation workflow could not be built or was malformed.",
            why: "A setting combination produced a workflow ComfyUI could not accept.",
            fixes: "Reset the affected settings and retry. || Try a default preset to confirm the setup works. || Report it with the settings you used.",
        },
        "io_permission" => CatalogEntry {
            title: "File access was denied",
            what: "The app could not read or write a needed file.",
            why: "The folder is protected, read-only, or owned by another process.",
            fixes: "Choose a folder your user account can write to. || Close any app locking the file. || Run from a location that is not write-protected.",
        },
        "missing_node" => CatalogEntry {
            title: "A required ComfyUI node is missing",
            what: "The workflow needs a custom node that is not installed.",
            why: "A custom node pack referenced by the workflow is not present.",
            fixes: "Re-run setup to reinstall bundled nodes. || Check the logs for the node name. || Report it if the node should ship with the app.",
        },
        "model_not_found" => CatalogEntry {
            title: "Model not found",
            what: "The requested model or checkpoint could not be located.",
            why: "It is not installed, was moved or renamed, or the folder is not indexed.",
            fixes: "Install the model from Model Hub. || Refresh the model list in Settings. || Confirm the file is in the correct models folder.",
        },
        "out_of_memory" => CatalogEntry {
            title: "Ran out of memory",
            what: "The GPU or system ran out of memory during generation.",
            why: "The resolution, batch size, or model is too large for available memory.",
            fixes: "Lower the resolution or batch size and retry. || Close other GPU-heavy apps. || Use a smaller or more quantized model.",
        },
        "python_env_broken" => CatalogEntry {
            title: "Python environment problem",
            what: "The bundled Python environment could not be used.",
            why: "The environment is missing, incomplete, or a package failed to import.",
            fixes: "Re-run setup to rebuild the environment. || Check the logs for the failing import. || Report it if setup keeps failing.",
        },
        "serialization" => CatalogEntry {
            title: "Could not read the data",
            what: "The app received data it could not parse.",
            why: "A response was malformed or a file was corrupted.",
            fixes: "Retry the action. || Restart the app. || Report it if it keeps happening.",
        },
        "unsupported_gpu" => CatalogEntry {
            title: "GPU not supported",
            what: "The app could not use your GPU for this operation.",
            why: "No compatible GPU or driver was detected, or the feature needs CUDA.",
            fixes: "Update your GPU drivers. || Confirm your GPU meets the requirements. || Report your GPU model if you think it should work.",
        },
        "websocket_dropped" => CatalogEntry {
            title: "Live connection dropped",
            what: "The realtime connection to ComfyUI closed unexpectedly.",
            why: "ComfyUI may have restarted, or the network connection was interrupted.",
            fixes: "Retry the action to reconnect. || Confirm ComfyUI is still running. || Restart ComfyUI if the problem persists.",
        },
        _ => return None,
    })
}
