// Reads src/lib/locales/en.ts and emits report-proxy/src/catalog_data.rs.
// Run from the repo root:  node report-proxy/scripts/extract-catalog.mjs
import { readFileSync, writeFileSync } from "node:fs";

const EN = "src/lib/locales/en.ts";
const OUT = "report-proxy/src/catalog_data.rs";

const text = readFileSync(EN, "utf8");
// Match lines like:  "errors.out_of_memory.what": "The GPU ...",
const re = /"errors\.([a-z0-9_]+)\.(title|what|why|fixes)":\s*"((?:[^"\\]|\\.)*)"/g;
const codes = {};
let m;
while ((m = re.exec(text)) !== null) {
  const [, code, field, value] = m;
  if (code === "card" || code === "report") continue; // UI strings, not error codes
  (codes[code] ??= {})[field] = value;
}

const rustEscape = (s) => JSON.stringify(s ?? ""); // JSON string literals are valid Rust string literals for this ASCII copy

const arms = Object.keys(codes)
  .sort()
  .map((code) => {
    const e = codes[code];
    return `        ${JSON.stringify(code)} => CatalogEntry {
            title: ${rustEscape(e.title)},
            what: ${rustEscape(e.what)},
            why: ${rustEscape(e.why)},
            fixes: ${rustEscape(e.fixes)},
        },`;
  })
  .join("\n");

const out = `// @generated by report-proxy/scripts/extract-catalog.mjs -- do not edit by hand.
// Regenerate after changing error copy in src/lib/locales/en.ts.

pub fn catalog_lookup(code: &str) -> Option<CatalogEntry> {
    Some(match code {
${arms}
        _ => return None,
    })
}
`;

writeFileSync(OUT, out);
console.log(`Wrote ${OUT} with ${Object.keys(codes).length} entries.`);
